### ISSUE TITLE
vendor 中相关的c++代码不能被自动索引，在clion中跳转不过去？

### ISSUE THREAD

**Issue by eytb2** [Ahren-Li/android-cmake-project#1]
你有出现这个问题没，怎么解决呢

**Comment by Ahren-Li** [comment]
vendor相关的定义一般都是
```makefile
LOCAL_MODULE := audio.primary.$(TARGET_BOARD_HARDWARE)
```
所以你需要在env_android.cmake里定义：
```cmake
set(TARGET_BOARD_HARDWARE "rk30")
```

如果vendor的Android.mk写的很复杂的话，估计不能很好的识别

**Comment by eytb2** [comment]
我研究了一下， 不能跳转的c文件是vendor中那个模块没有配置mk或者bp， 比如ffmpeg， 能强行配置某一个文件夹或者一个模块内的文件嘛？

**Comment by Ahren-Li** [comment]
你可以参考下这个文件：https://github.com/Ahren-Li/android-cmake-project/blob/automatic/Cmake/old/libui.cmake

你可以在主CMakeList.txt 最后一行 include 你手动编写的模块cmake
