### ISSUE TITLE
Clion建立项目时测试Clang编译失败，原因时out目录拼接结果不正确，实际原因是缺少ARCH_VARIANT

### ISSUE THREAD

**Issue by NasdaqGodzilla** [Ahren-Li/android-cmake-project#10]
Clang检测失败，out目录拼接时因$ANDROID_ARCH_VARIANT为空导致拼接结果不对，找不到生成文件，致使CLion认为Clang不可用，环境不到位。

修改方案为为CMake添加对应的环境参数，已提PR: https://github.com/Ahren-Li/android-cmake-project/pull/9

**Comment by Ahren-Li** [comment]
其实，那个默认的env，我认为大家是不会用的，
$(android_source_tree)/android.env.cmake  我觉得大家应该会自己配置的
