### ISSUE TITLE
do not support headerLibraries & cc_library_headers when parse android.bp  

### ISSUE THREAD

**Issue by SuperSaiyan30** [Ahren-Li/android-cmake-project#2]
bp files in android code path can not parse correct

frameworks/native/libs/vr/libdvr/Android.bp
frameworks/native/libs/vr/libvrflinger/Android.bp

**Comment by Ahren-Li** [comment]
I will fix the problem. Thank you

**Comment by Ahren-Li** [comment]
At present, the support of the project is temporarily suspended, and the focus is on the development of soong-cmake, which has better compatibility
