### ISSUE TITLE
CMake Error 

### ISSUE THREAD

**Issue by JantHsueh** [Ahren-Li/android-cmake-project#3]
你好，看到你的这个项目，非常激动，但是我在运行中遇到了很多系列问题

环境：
windows 10
CLion 2019.2
NDK  21.1.6352462
Android 源码：8.0.0_r1

报下面的错误，我的Android 源码中，并没有out 这个目录，源码是在Ubuntu 18.04 上编译通过的

![image](https://user-images.githubusercontent.com/13702466/82728687-b0dedb00-9d24-11ea-9f49-ee27461cab5a.png)

下面是详细的错误信息，请大佬帮忙看一下是什么问题，非常感谢，可否留个联系方式呢？我在你的博客中找了很久，没有找到

`"D:\JetBrains\CLion 2019.2\bin\cmake\win\bin\cmake.exe" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=D:/msys64/mingw64/bin/clang.exe -DCMAKE_CXX_COMPILER=D:/msys64/mingw64/bin/clang++.exe -D_CMAKE_TOOLCHAIN_PREFIX=llvm- -G "CodeBlocks - MinGW Makefiles" E:\AndroidStudioProjects\aosp\aosp
-- Check for working C compiler: C:/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Check for working C compiler: C:/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- broken
CMake Error at D:/JetBrains/CLion 2019.2/bin/cmake/win/share/cmake-3.14/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "C:/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: E:/AndroidStudioProjects/aosp/aosp/cmake-build-debug/CMakeFiles/CMakeTmp
    
    Run Build Command(s):D:/MinGW/bin/mingw32-make.exe cmTC_ad5ae/fast 
    D:/MinGW/bin/mingw32-make.exe -f CMakeFiles\cmTC_ad5ae.dir\build.make CMakeFiles/cmTC_ad5ae.dir/build
    mingw32-make.exe[1]: Entering directory 'E:/AndroidStudioProjects/aosp/aosp/cmake-build-debug/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_ad5ae.dir/testCCompiler.c.o
    C:\Android\Sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe --gcc-toolchain=C:/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64   -fno-exceptions -Wno-multichar -fno-strict-aliasing -Werror=pointer-to-int-cast -Werror=int-to-pointer-cast -Werror=implicit-function-declaration -ffunction-sections -fdata-sections -funwind-tables -fstack-protector-strong -Wa,--noexecstack -Werror=format-security -D_FORTIFY_SOURCE=2 -fno-short-enums -no-canonical-prefixes -march=armv8-a -mcpu=cortex-a53 -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=date-time -D__compiler_offsetof=__builtin_offsetof -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -Wno-expansion-to-defined -ffunction-sections -fdata-sections -fno-short-enums -funwind-tables -fstack-protector-strong -fdebug-prefix-map=E:/AndroidStudioProjects/aosp/aosp/= -nostdlibinc -target aarch64-linux-android -BC:/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin -fno-rtti -fpie -D_USING_LIBCXX -DANDROID_STRICT -std=gnu99 -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=address-of-temporary -Werror=null-dereference -Werror=return-type -Wno-tautological-constant-compare -Wno-null-pointer-arithmetic -Wno-enum-compare -Wno-enum-compare-switch -DPLATFORM_SDK_VERSION=26    -o CMakeFiles\cmTC_ad5ae.dir\testCCompiler.c.o   -c E:\AndroidStudioProjects\aosp\aosp\cmake-build-debug\CMakeFiles\CMakeTmp\testCCompiler.c
    Linking C executable cmTC_ad5ae
    "D:\JetBrains\CLion 2019.2\bin\cmake\win\bin\cmake.exe" -E cmake_link_script CMakeFiles\cmTC_ad5ae.dir\link.txt --verbose=1
    C:\Android\Sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe --gcc-toolchain=C:/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64 -pie -nostdlib -Bdynamic -Wl,-dynamic-linker,/system/bin/linker64 -Wl,--gc-sections -Wl,-z,nocopyreloc -Wl,-rpath-link=E:/AndroidStudioProjects/aosp/aosp/out/target/product/rk3399/obj/lib -LE:/AndroidStudioProjects/aosp/aosp/out/target/product/rk3399/obj/lib E:/AndroidStudioProjects/aosp/aosp/out/target/product/rk3399/obj/lib/crtbegin_dynamic.o  CMakeFiles/cmTC_ad5ae.dir/testCCompiler.c.o -Wl,--no-whole-archive E:/AndroidStudioProjects/aosp/aosp/out/target/product/rk3399/obj/STATIC_LIBRARIES/libclang_rt.ubsan_minimal-aarch64-android_intermediates/libclang_rt.ubsan_minimal-aarch64-android.a E:/AndroidStudioProjects/aosp/aosp/out/target/product/rk3399/obj/STATIC_LIBRARIES/libcompiler_rt-extras_intermediates/libcompiler_rt-extras.a E:/AndroidStudioProjects/aosp/aosp/out/target/product/rk3399/obj/STATIC_LIBRARIES/libatomic_intermediates/libatomic.a E:/AndroidStudioProjects/aosp/aosp/out/target/product/rk3399/obj/STATIC_LIBRARIES/libgcc_intermediates/libgcc.a -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--build-id=md5 -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined-version -Wl,-m,aarch64_elf64_le_vec -Wl,--hash-style=gnu -fuse-ld=gold -Wl,--icf=safe -Wl,--fix-cortex-a53-843419 -target aarch64-linux-android -BC:/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin -Wl,--exclude-libs,libclang_rt.ubsan_minimal-aarch64-android.a -Wl,--no-undefined -lc++ -lc -lm -ldl -o cmTC_ad5ae E:/AndroidStudioProjects/aosp/aosp/out/target/product/rk3399/obj/lib/crtend_android.o 
    clang.exe: error: no such file or directory: 'E:/AndroidStudioProjects/aosp/aosp/out/target/product/rk3399/obj/lib/crtbegin_dynamic.o'
    clang.exe: error: no such file or directory: 'E:/AndroidStudioProjects/aosp/aosp/out/target/product/rk3399/obj/STATIC_LIBRARIES/libclang_rt.ubsan_minimal-aarch64-android_intermediates/libclang_rt.ubsan_minimal-aarch64-android.a'
    clang.exe: error: no such file or directory: 'E:/AndroidStudioProjects/aosp/aosp/out/target/product/rk3399/obj/STATIC_LIBRARIES/libcompiler_rt-extras_intermediates/libcompiler_rt-extras.a'
    clang.exe: error: no such file or directory: 'E:/AndroidStudioProjects/aosp/aosp/out/target/product/rk3399/obj/STATIC_LIBRARIES/libatomic_intermediates/libatomic.a'
    clang.exe: error: no such file or directory: 'E:/AndroidStudioProjects/aosp/aosp/out/target/product/rk3399/obj/STATIC_LIBRARIES/libgcc_intermediates/libgcc.a'
    clang.exe: error: no such file or directory: 'E:/AndroidStudioProjects/aosp/aosp/out/target/product/rk3399/obj/lib/crtend_android.o'
    CMakeFiles\cmTC_ad5ae.dir\build.make:85: recipe for target 'cmTC_ad5ae' failed
    mingw32-make.exe[1]: *** [cmTC_ad5ae] Error 1
    mingw32-make.exe[1]: Leaving directory 'E:/AndroidStudioProjects/aosp/aosp/cmake-build-debug/CMakeFiles/CMakeTmp'
    Makefile:120: recipe for target 'cmTC_ad5ae/fast' failed
    mingw32-make.exe: *** [cmTC_ad5ae/fast] Error 2
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:9 (project)

-- Configuring incomplete, errors occurred!
See also "E:/AndroidStudioProjects/aosp/aosp/cmake-build-debug/CMakeFiles/CMakeOutput.log".
See also "E:/AndroidStudioProjects/aosp/aosp/cmake-build-debug/CMakeFiles/CMakeError.log".
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_C_COMPILER= D:/msys64/mingw64/bin/clang.exe
CMAKE_CXX_COMPILER= D:/msys64/mingw64/bin/clang++.exe

-- Generating done
-- Build files have been written to: E:/AndroidStudioProjects/aosp/aosp/cmake-build-debug

[Finished]`

**Comment by Ahren-Li** [comment]
你lunch的时候也是rk3399-userdebug?

**Comment by Ahren-Li** [comment]
你把out也copy出来吧，有些中间文件会有依赖的
