### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by eytb2** [Ahren-Li/android-cmake-project#4]
parseAndroidMK: SHARED android.hardware.graphics.allocator-2.0 not found!
parseAndroidMK: SHARED android.hardware.graphics.common-1.1 not found!
parseAndroidMK: SHARED android.hardware.graphics.mapper-2.0 not found!
parseAndroidMK: SHARED android.hardware.graphics.mapper-2.1 not found!
parseAndroidMK: SHARED android.hardware.configstore-1.0 not found!

这个问题有什么影响吗？
另外get_build_var TARGET_BOARD_HARDWARE    无任何结果

**Comment by Ahren-Li** [comment]
HWDL服务目前还无法索引，后面会慢慢转向用soong解析。

TARGET_BOARD_HARDWARE一般都会有，这个是平台相关定义，在RK平台这个是HAL so的后缀名称。
