### ISSUE TITLE
CMake Error: Cannot determine link language for target "libtrace_proto_STATIC". CMake Error: CMake can not determine linker language for target: libtrace_proto_STATIC

### ISSUE THREAD

**Issue by ebitgeek** [Ahren-Li/android-cmake-project#5]
/home/luo/Programs/clion/bin/cmake/linux/bin/cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" /home/luo/AndroidStudioProjects/AndroidSource/aosp
Hello from Android build!
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/services/surfaceflinger/Android.bp
addTarget: libsurfaceflinger_SHARED
parseAndroidMK: SHARED android.frameworks.vr.composer-1.0 not found!
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/hardware/interfaces/configstore/utils/Android.bp
addTarget: android.hardware.configstore-utils_SHARED
parseAndroidMK: SHARED android.hardware.configstore-1.0 not found!
parseAndroidMK: SHARED android.hardware.configstore-1.1 not found!
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/system/core/base/Android.bp
addTarget: libbase_SHARED
AndroidMK:/home/luo/AndroidStudioProjects/AndroidSource/aosp/system/core/liblog/Android.mk
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/system/core/liblog/Android.bp
addTarget: liblog_SHARED
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/system/libhidl/base/Android.bp
addTarget: libhidlbase_SHARED
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/system/core/libcutils/Android.bp
addTarget: libcutils_SHARED
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/system/core/libutils/Android.bp
addTarget: libutils_SHARED
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/bionic/libdl/Android.bp
addTarget: libdl_SHARED
AndroidMK:/home/luo/AndroidStudioProjects/AndroidSource/aosp/bionic/linker/Android.mk
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/bionic/linker/Android.bp
addTarget: ld-android_SHARED
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/bionic/libdl/Android.bp
addTarget: libdl_static_STATIC
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/system/core/libvndksupport/Android.bp
addTarget: libvndksupport_SHARED
parseAndroidMK: SHARED android.hardware.configstore-1.0 not found!
parseAndroidMK: SHARED android.hardware.configstore-1.1 not found!
parseAndroidMK: SHARED android.hardware.graphics.allocator-2.0 not found!
parseAndroidMK: SHARED android.hardware.graphics.composer-2.1 not found!
parseAndroidMK: SHARED android.hardware.graphics.composer-2.2 not found!
parseAndroidMK: SHARED android.hardware.power-1.0 not found!
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/libs/binder/Android.bp
addTarget: libbinder_SHARED
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/system/core/libutils/Android.bp
addTarget: libutilscallstack_SHARED
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/system/core/libbacktrace/Android.bp
addTarget: libbacktrace_SHARED
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/external/libunwind/Android.bp
addTarget: libunwind_SHARED
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/external/lzma/C/Android.bp
addTarget: liblzma_SHARED
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/system/core/libunwindstack/Android.bp
addTarget: libunwindstack_SHARED
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/art/libdexfile/Android.bp
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/system/core/libunwindstack/Android.bp
addTarget: libunwindstack_dex_STATIC
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/art/libdexfile/Android.bp
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/art/libdexfile/Android.bp
AndroidMK:/home/luo/AndroidStudioProjects/AndroidSource/aosp/system/core/demangle/Android.mk
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/system/core/demangle/Android.bp
addTarget: libdemangle_STATIC
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/bionic/libc/async_safe/Android.bp
addTarget: libasync_safe_STATIC
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/system/core/libcutils/Android.bp
addTarget: libcutils_STATIC
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/libs/vr/libbufferhubqueue/Android.bp
addTarget: libbufferhubqueue_SHARED
AndroidMK:/home/luo/AndroidStudioProjects/AndroidSource/aosp/hardware/libhardware/Android.mk
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/hardware/libhardware/Android.bp
addTarget: libhardware_SHARED
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/libs/ui/Android.bp
addTarget: libui_SHARED
parseAndroidMK: SHARED android.hardware.graphics.allocator-2.0 not found!
parseAndroidMK: SHARED android.hardware.graphics.common-1.1 not found!
parseAndroidMK: SHARED android.hardware.graphics.mapper-2.0 not found!
parseAndroidMK: SHARED android.hardware.graphics.mapper-2.1 not found!
parseAndroidMK: SHARED android.hardware.configstore-1.0 not found!
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/system/libhidl/transport/Android.bp
addTarget: libhidltransport_SHARED
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/system/libhwbinder/Android.bp
addTarget: libhwbinder_SHARED
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/system/core/libsync/Android.bp
addTarget: libsync_SHARED
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/libs/arect/Android.bp
-- libarect_STATIC: null src, continue and skip.
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/system/core/libgrallocusage/Android.bp
addTarget: libgrallocusage_STATIC
parseAndroidMK: SHARED android.hardware.graphics.allocator-2.0 not found!
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/libs/math/Android.bp
-- libmath_STATIC: null src, continue and skip.
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/libs/vr/libpdx_default_transport/Android.bp
-- libpdx_default_transport_SHARED: null src, continue and skip.
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/libs/vr/libbufferhub/Android.bp
addTarget: libbufferhub_STATIC
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/libs/nativewindow/Android.bp
addTarget: libnativewindow_SHARED
parseAndroidMK: SHARED android.hardware.graphics.common-1.1 not found!
AndroidMK:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/opengl/libs/Android.mk
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/opengl/libs/Android.bp
addTarget: libEGL_SHARED
parseAndroidMK: SHARED android.hardware.configstore-1.0 not found!
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/libs/graphicsenv/Android.bp
addTarget: libgraphicsenv_SHARED
AndroidMK:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/opengl/libs/Android.mk
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/opengl/libs/Android.bp
addTarget: libEGL_getProcAddress_STATIC
AndroidMK:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/opengl/libs/Android.mk
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/opengl/libs/Android.bp
addTarget: libEGL_blobCache_STATIC
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/system/libfmq/Android.bp
addTarget: libfmq_SHARED
AndroidMK:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/opengl/libs/Android.mk
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/opengl/libs/Android.bp
addTarget: libGLESv1_CM_SHARED
AndroidMK:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/opengl/libs/Android.mk
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/opengl/libs/Android.bp
addTarget: libGLESv2_SHARED
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/libs/gui/Android.bp
addTarget: libgui_SHARED
parseAndroidMK: SHARED android.hardware.graphics.common-1.1 not found!
parseAndroidMK: SHARED android.hidl.token-1.0-utils not found!
parseAndroidMK: SHARED android.hardware.graphics.bufferqueue-1.0 not found!
parseAndroidMK: SHARED android.hardware.configstore-1.0 not found!
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/services/surfaceflinger/layerproto/Android.bp
addTarget: liblayers_proto_SHARED
parseAndroidMK: SHARED android.hardware.graphics.common-1.1 not found!
AndroidMK:/home/luo/AndroidStudioProjects/AndroidSource/aosp/external/protobuf/Android.mk
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/external/protobuf/Android.bp
addTarget: libprotobuf-cpp-lite_SHARED
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/services/surfaceflinger/TimeStats/timestatsproto/Android.bp
addTarget: libtimestats_proto_SHARED
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/vulkan/libvulkan/Android.bp
addTarget: libvulkan_SHARED
parseAndroidMK: SHARED android.hardware.configstore-1.0 not found!
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/system/core/libziparchive/Android.bp
addTarget: libziparchive_SHARED
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/external/zlib/Android.bp
addTarget: libz_SHARED
parseAndroidMK: SHARED android.hardware.graphics.common-1.0 not found!
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/services/utils/Android.bp
addTarget: libserviceutils_STATIC
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/cmds/surfacereplayer/proto/Android.bp
addTarget: libtrace_proto_STATIC
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/vulkan/vkjson/Android.bp
addTarget: libvkjson_STATIC
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/external/jsoncpp/Android.bp
addTarget: libjsoncpp_STATIC
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/libs/vr/libvr_manager/Android.bp
addTarget: libvr_manager_STATIC
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/system/core/libutils/Android.bp
addTarget: libutils_STATIC
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/libs/binder/Android.bp
addTarget: libbinder_STATIC
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/libs/vr/libvrflinger/Android.bp
addTarget: libvrflinger_STATIC
parseAndroidMK: SHARED android.frameworks.vr.composer-1.0 not found!
parseAndroidMK: SHARED android.hardware.graphics.allocator-2.0 not found!
parseAndroidMK: SHARED android.hardware.graphics.composer-2.1 not found!
parseAndroidMK: SHARED android.hardware.graphics.composer-2.2 not found!
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/libs/vr/libdisplay/Android.bp
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/libs/vr/libdvrcommon/Android.bp
-- libdvrcommon_STATIC: null src, continue and skip.
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/libs/vr/libperformance/Android.bp
addTarget: libperformance_STATIC
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/libs/vr/libvrsensor/Android.bp
addTarget: libvrsensor_STATIC
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/libs/vr/libdisplay/Android.bp
AndroidBP:/home/luo/AndroidStudioProjects/AndroidSource/aosp/frameworks/native/libs/vr/libbroadcastring/Android.bp
-- libbroadcastring_STATIC: null src, continue and skip.
-- Configuring done
CMake Error: Cannot determine link language for target "libtrace_proto_STATIC".
CMake Error: CMake can not determine linker language for target: libtrace_proto_STATIC
-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by Ahren-Li** [comment]
主要是 srcs 中没有.cpp/.c 扩展的源文件
frameworks/native/cmds/surfacereplayer/proto/Android.bp
```
cc_library_static {
    name: "libtrace_proto",
    srcs: [
        "src/trace.proto",
    ],
    cflags: [
        "-Wall",
        "-Werror",
    ],
    proto: {
        type: "lite",
        export_proto_headers: true,
    },
}

你可以暂时先把这个bp文件给屏蔽试试，目前还没有文件过滤机制
```

**Comment by Ahren-Li** [comment]
done, 待新项目 android soong project解决
