### ISSUE TITLE
Cmake 无法 load

### ISSUE THREAD

**Issue by huizai0613** [Ahren-Li/android-cmake-project#7]
一直卡在 file(STRINGS ${PROJECT_DIR}/out/target/product/${ANDROID_LUNCH}/module-info.json MyFile REGEX ".*(SHARED_LIBRARIES|STATIC_LIBRARIES|EXECUTABLES).*")，请问怎么办，我qq：393915707 可以指导下么谢谢

**Comment by Ahren-Li** [comment]
你的CMake的版本是多少，换个比较新的版本试试。

**Comment by huizai0613** [comment]
Ahren-Li ,我新人,有挺多问题的,麻烦能直接沟通一下 ,谢谢!!不介意付费咨询

**Comment by Ahren-Li** [comment]
done
